### ISSUE TITLE
Orphaned project?

### ISSUE THREAD

**Issue by geoffjay** [opendcs/opendcs#1]
I was really hoping to grab OpenDCS as an organization name. Any chance this is orphaned and you're willing to let me have it? Pretty please.

**Comment by geoffjay** [comment]
Is that a no?

**Comment by opendcs** [comment]
Sorry. The last email got away from me. I meant to reply.
We snagged the 'opendcs' name because we maintain an open source package 
used by several government agencies to collect environmental data. The 
name of the package is 'OpenDCS', for open-source Data Collection 
System. So it's not an orphaned project. We do intend to use it.

Best regards,
Mike Maloney

On 10/23/15 2:12 PM, Geoff Johnson wrote:
>
> Is that a no?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/opendcs/opendcs/issues/1#issuecomment-150651828>.
>

-- 
Michael Maloney
Cove Software LLC
6030 Marshalee Dr., Ste 607
Elkridge, MD 21075-5935
Tel: (410) 715-1117
Email: mike@covesw.com
Skype: mjmilex

**Comment by geoffjay** [comment]
In the last (almost) year I've noticed that there has not been any movement in this organization/repository so I thought I'd check again to see if there's any chance that it's been orphaned. I've been working with the organization [open-dcs](https://github.com/open-dcs) along with these [gh-pages](https://open-dcs.github.io).

The project that I'm working on is an open source Distributed Control System which is based off of software that we have been working on for about 5 years under a different name. I actually think that if you haven't already done any code for your application there's a possibility that whatever you're trying to do could be done within our software by writing a plugin, this is how we add support for random acquisition hardware. Provided that you don't mind working with GObject and C/Vala/Python.

Anyways, just making another plea. The difference between opendcs and open-dcs probably seems trivial, but I'm easily bothered by trivial things.
