### ISSUE TITLE
Unable to save/create new algorithm in computation editor - client OPENDCS 7.0.4 - ORA-02289

### ISSUE THREAD

**Issue by zamusacelre** [opendcs/opendcs#171]
**Unable to save/create new algorithm in computation editor - using client OPENDCS 7.0.4**
When I try creating a new algorithm and savings it it won't save. I get an error.  I have tried changing the name (to shorter title), tried closing and reopening the GUI, made sure I try saving immediately after opening.  No matter what I keep getting the same error.

**To Reproduce**
1. Launch the client version of OPENDCS 7.0.4
2. Go to Computation Editor
3. On Algorithm Tab click on "New"
4. Create an algorithm - using exec class : decodes.tsdb.algo.PythonAlgorithm 
5. Click "Commit" and then see error

**Expected behavior**
Save new algorithm and all content entered .

**Screenshots**
![image](https://user-images.githubusercontent.com/104451600/215793328-cb4317e7-aae0-4f40-83a9-2117a943b8ab.png)

**Desktop/ServerSide (please complete the following information):**
 - OPENDCS 7.0.4
 - Windows client

**Additional context**

**Comment by MikeNeilson** [comment]
I’m not sure why it would be happening now and not earlier in your usage but try changing this line in user.properties

sqlKeyGenerator=decodes.sql.OracleSequenceKeyGenerator

to this:

sqlKeyGenerator=decodes.sql.OracleSequenceKeyGenerator

Mike

From: zamusacelre ***@***.***>
Sent: Tuesday, January 31, 2023 6:51 AM
To: opendcs/opendcs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [URL Verdict: Neutral][Non-DoD Source] [opendcs/opendcs] Unable to save/create new algorithm in computation editor - client OPENDCS 7.0.4 - ORA-02289 (Issue #171)


Unable to save/create new algorithm in computation editor - using client OPENDCS 7.0.4
When I try creating a new algorithm and savings it it won't save. I get an error. I have tried changing the name (to shorter title), tried closing and reopening the GUI, made sure I try saving immediately after opening. No matter what I keep getting the same error.

To Reproduce
Steps to reproduce the behavior:

  1.  Launch the client version of OPENDCS 7.0.4
  2.  Go to Computation Editor
  3.  On Algorithm Tab click on "New"
  4.  Create an algorithm - using exec class : decodes.tsdb.algo.PythonAlgorithm
  5.  Click "Commit" and then see error

Expected behavior
Save new algorithm and all content entered .

Screenshots
[image]<https://user-images.githubusercontent.com/104451600/215793328-cb4317e7-aae0-4f40-83a9-2117a943b8ab.png>

Desktop/ServerSide (please complete the following information):

  *   OPENDCS 7.0.4
  *   Windows client

Additional context

**Comment by MikeNeilson** [comment]
I just checked your database, the version shows 14, should be 68 for this to work right. Wierd that it only came up now.

We can schedule a time outside github to do the schema update.
