### ISSUE TITLE
Jython requests library missing from 7.0.3+ releases

### ISSUE THREAD

**Issue by agilmore2** [opendcs/opendcs#180]
**Describe the bug**
OpenDCS at least as far back as 6.8rc15 through 7.0.2 installs the python requests library in the "dep" directory. 7.0.4 does not have this library present, which is causing missing computations.

```
$ find 6.8.15 7.0.2 7.0.4 -iname *request*
./6.8.15/dep/Lib/site-packages/pip/_vendor/urllib3/util/request$py.class
./6.8.15/dep/Lib/site-packages/pip/_vendor/urllib3/util/request.py
./6.8.15/dep/Lib/site-packages/pip/_vendor/urllib3/request$py.class
./6.8.15/dep/Lib/site-packages/pip/_vendor/urllib3/request.py
./6.8.15/dep/Lib/site-packages/pip/_vendor/requests
./7.0.2/dep/Lib/site-packages/pip/_vendor/requests
./7.0.2/dep/Lib/site-packages/pip/_vendor/urllib3/request$py.class
./7.0.2/dep/Lib/site-packages/pip/_vendor/urllib3/request.py
./7.0.2/dep/Lib/site-packages/pip/_vendor/urllib3/util/request$py.class
./7.0.2/dep/Lib/site-packages/pip/_vendor/urllib3/util/request.py
```

**Expected behavior**
Python request library ships with OpenDCS.

This is a high priority issue for Reclamation users.

**Comment by agilmore2** [comment]
@MikeNeilson let's use this issue.

Can you tell which PR resulted in this change?

**Comment by MikeNeilson** [comment]
I'd have to really dig and the moment i'm holding a baby. But we never
otherwise tweaked the jython so just going to a known "good" the yank the
right jython packages should work.

**Comment by agilmore2** [comment]
I am very puzzled because I don't see any changes to the build configs
between 7.0.2 and 7.0.4. I see a bunch between 7.0.1 and 7.0.4, so perhaps
I missed the last good version.

**Comment by MikeNeilson** [comment]
Well, as dumb luck would have it, I still have a copy of that whole directory in my home dev environment.
I don't want to just yank the whole thing again but I'm testing an idea to embedded such projects in the opendcs jar. Probably won't finish tonight though but can pick it up again in the morning.

**Comment by agilmore2** [comment]
Sounds good. Glad to hear you have that setup.

**Comment by MikeNeilson** [comment]
So things didn't work quite as easy as I wanted but I've got a stopgap for you to get back in service.

Within each script, or PyAlgoEnv.py (should be in the python directory in DCSTOOL_HOME)

you can do a
```
import sys
sys.path.append("a known folder")

```

In that known folder, take the "requests" folder from an existing opendcs 6.8 install and just put it there. That should let the library be picked up.

I'd like to spend a little more time with jython and how it's "classpath" works so we can make something a little more formal and cleaner for future additional library installs. At least if that stopgap works for y'all for now. Otherwise I have one dirty trick to try latter and we can just generate a new release.
