### ISSUE TITLE
Migrate various unit tests within existing classes to junit5 unit tests

### ISSUE THREAD

**Issue by MikeNeilson** [opendcs/opendcs#25]

**Comment by MikeNeilson** [comment]
The low hanging fruit anyways, from the several I saw some of them expected much more infrastructure. but the more that's in any test automation the better.

**Comment by adamkorynta** [comment]
The following PR's cover migrating some low hanging fruit to JUnit 5 as well as deleting tests that no longer make sense due to unused features or exploratory JDK testing.

https://github.com/opendcs/opendcs/pull/155
https://github.com/opendcs/opendcs/pull/156
https://github.com/opendcs/opendcs/pull/157
