### ISSUE TITLE
"Display Next" in msgaccess doesn't

### ISSUE THREAD

**Issue by agilmore2** [opendcs/opendcs#540]
**Describe the bug**
The Display Next button shows the same message over and over again when a single platform is in the search criteria

**To Reproduce**
1. Start DCP Message Browser
2. Connect to an LRGS
3. Edit Search Criteria and put in a single platform (I chose BCC03B50)
4. Hit Display Next button twice
5. Note that the same message is displayed twice, and will continue to show up

**Expected behavior**
Display Next moves through the available messages for the platform based on the Date/Time range of the Search Criteria

**Screenshots**
![image](https://github.com/opendcs/opendcs/assets/6852298/cd12b482-5ef1-451f-b028-691809f65a6b)

**Desktop/ServerSide (please complete the following information):**
 - OS: Fedora 37
 - Version OpenDCS 7.0.12

**Additional context**
First reported by Bruce Smiley, BCHydro

**Comment by MikeNeilson** [comment]
That was easy to recreate. Display all did work and provide different results.

**Comment by agilmore2** [comment]
Reproduced in the 6.8.15 version that Reclamation uses.

**Comment by MikeNeilson** [comment]
I suspect that's likely always been an issue. I'm not sure the last time that code was touch, the commit history got a bit messed up during one of the migrations, or our rewrite thereof to remove a binary for licensing issues.

So certainly a good catch and report, I've done that more than once and never noticed, probably because I didn't limit things to one ID.

Are you going to try working on the fix for this? If so, FYI, there's some LRGS tests in place now, but fairly limited in structure... only got to the point of verifying the archive works but maybe useful in this case to see if the issues is in the archive search itself of the DDS connection implementation.
