### ISSUE TITLE
HDB headless install impossible

### ISSUE THREAD

**Issue by agilmore2** [opendcs/opendcs#81]
Since we are producing one installer without HDB components by default, HDB installs on headless servers are not working without manually copying at least the ojdbcX.jar file.

java -jar <opendcsinstaller.jar> -console or -properties <file> do not give the option of installing the HDB components. It doesn't look like our version of izPack allows this.

We either need to produce an HDB specific installer, an HDB specific server tarball, or find a way to select optional components in a headless install.

**Comment by MikeNeilson** [comment]
It works correctly with the 7.1.0 installer that gets made. So it should be fixable.

**Comment by MikeNeilson** [comment]
it's a bug in izpack < 4.3.5. working on updating it now.

**Comment by MikeNeilson** [comment]
Huh. I swear I tested that. I’ll investigate later.

From: agilmore2 ***@***.***>
Sent: Thursday, August 4, 2022 11:22 AM
To: opendcs/opendcs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [URL Verdict: Neutral][Non-DoD Source] [opendcs/opendcs] HDB headless install impossible (Issue #81)


Since we are producing one installer without HDB components by default, HDB installs on headless servers are not working without manually copying at least the ojdbcX.jar file.

java -jar <opendcsinstaller.jar> -console or -properties do not give the option of installing the HDB components. It doesn't look like our version of izPack allows this.

We either need to produce an HDB specific installer, an HDB specific server tarball, or find a way to select optional components in a headless install.
