### ISSUE TITLE
Java 11 runtime support?

### ISSUE THREAD

**Issue by agilmore2** [opendcs/opendcs#92]
Users are being pushed to upgrade to Java 11 on the headless server side. Are there incompatibilities we need to be aware of? There's deprecation warnings in algorithms, but I'm not sure what else.

**Comment by MikeNeilson** [comment]
Not that I'm currently aware of beyond algoedit won't be able to compile anymore (tool.jar was removed in 9).

Most of my runtime testing is java 11 only using java 8 to build.

In generally I've found as long as you have good 8 compat you have decent 11 compat, the begin thing in 11 is extra stream() functions and the var keyboard and some deprecated things getting removed.

javafx is also no longer bundled but we're not using it at all so that doesn't really affect us.

If we want to keep algoedit around we'll need to find a different compiler to bundle (they do exist), alternatively we can drop that in favor of better IDE support and jar distribution.

**Comment by MikeNeilson** [comment]
Update, Ive been testing a lot, mostly because I wasn't paying attention to the JVM with Java 17 lately. Only oddity I had was two threads not being correctly set to daemon thread mode we're keeping the JVM alive after the rest of the application exited.

That should just be fixed in one of my current PRs though.

**Comment by MikeNeilson** [comment]
So the one thing I've seen being an issue (and I've gone with a runtime as high as 17) is that our threads keep the application open when they should shutdown.

I've got a few of the threads corrected to daemon threads in https://github.com/opendcs/opendcs/pull/254 however some shouldn't be daemon threads but don't properly get their shutdown variable set. I know I caught at least one of those in #254 but I suspect their are more.


To identify what's keeping the JVM open you can use VisualVM, JConsole, or jstack to see which threads are still in a wait state.

I think i've got most of the threads to have an obvious name, but otherwise the numbered threads are the ones to look for.

**Comment by MikeNeilson** [comment]
Going to close this. Pretty confident we support java 11 without issue, other than AlgoEdit as stated.
